param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\IAR 8.32\IAR_System\common\bin\cspybat" -f "D:\15届智能车\RT1021\我的RT1021代码\RT1021小车程序\Project\IAR\program\settings\RT102X.nor_zf_ram.general.xcl" --backend -f "D:\15届智能车\RT1021\我的RT1021代码\RT1021小车程序\Project\IAR\program\settings\RT102X.nor_zf_ram.driver.xcl" 
}
else
{
& "C:\IAR 8.32\IAR_System\common\bin\cspybat" -f "D:\15届智能车\RT1021\我的RT1021代码\RT1021小车程序\Project\IAR\program\settings\RT102X.nor_zf_ram.general.xcl" --debug_file=$debugfile --backend -f "D:\15届智能车\RT1021\我的RT1021代码\RT1021小车程序\Project\IAR\program\settings\RT102X.nor_zf_ram.driver.xcl" 
}
